id: I27991460
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:11:43+00:00'
last_modified: '2022-06-09T06:38:43.994075+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5149
  title: ལང་ཚོའི་རྦབ་ཆུ་དང་ལྗགས་རྩོམ་བདམས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    DC28:
      image_group_id: I1KG5158
      title: Volume 1 of lang tsho'i rbab chu dang ljags rtsom bdams sgrig
      total_pages: 262
      order: 1
      base_file: DC28.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
