id: P007855
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:45:14.346949
source_metadata:
  id: bdr:W1KG5149
  title: ལང་ཚོའི་རྦབ་ཆུ་དང་ལྗགས་རྩོམ་བདམས་སྒྲིག
  author: ''
  volumes:
    d31f77035adb4e3d8dd6c9190a7bf475:
      image_group_id: I1KG5158
      title: Volume 1 of lang tsho'i rbab chu dang ljags rtsom bdams sgrig
      volume_number: 1
      total_pages: 262
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
