id: P007855
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5149
  title: ལང་ཚོའི་རྦབ་ཆུ་དང་ལྗགས་རྩོམ་བདམས་སྒྲིག
  author: ''
  volumes:
    f26bf93ac91b46199ac23d779b475bd2:
      image_group_id: I1KG5158
      title: ''
      volume_number: 1
      total_pages: 262
ebook_metadata:
  title: ལང་ཚོའི་རྦབ་ཆུ་དང་ལྗགས་རྩོམ་བདམས་སྒྲིག
  author: ''
  sku: P007855
  cover: cover.jpg
  layers:
  - pagination
